"""
Certificate Revocation Models

Defines CRL (Certificate Revocation List) and OCSP-related models
for checking certificate validity status.
"""

from django.db import models
from django.utils import timezone
import uuid


class CertificateRevocationList(models.Model):
    """
    X.509 Certificate Revocation List (CRL).
    
    CRLs are periodically generated by CAs to list all revoked certificates.
    Clients can download CRLs to check if a certificate has been revoked.
    """
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    # Issuing CA
    issuing_ca = models.ForeignKey(
        'CertificateAuthority',
        on_delete=models.CASCADE,
        related_name='crls'
    )
    
    # CRL Identification
    crl_number = models.IntegerField(
        help_text="Monotonically increasing CRL number"
    )
    
    # Validity
    this_update = models.DateTimeField(
        help_text="CRL issuance time"
    )
    next_update = models.DateTimeField(
        help_text="Expected next CRL issuance"
    )
    
    # CRL Data
    crl_pem = models.TextField(
        help_text="CRL in PEM format"
    )
    crl_der = models.BinaryField(
        null=True,
        blank=True,
        help_text="CRL in DER format"
    )
    
    # Signature
    signature_algorithm = models.CharField(max_length=50)
    
    # Statistics
    entries_count = models.IntegerField(
        default=0,
        help_text="Number of revoked certificates in this CRL"
    )
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = "Certificate Revocation List"
        verbose_name_plural = "Certificate Revocation Lists"
        ordering = ['-crl_number']
        unique_together = ['issuing_ca', 'crl_number']
    
    def __str__(self):
        return f"CRL #{self.crl_number} - {self.issuing_ca.name}"
    
    def is_current(self):
        """Check if this CRL is still current"""
        return timezone.now() < self.next_update


class RevokedCertificate(models.Model):
    """
    Individual entry in a CRL representing a revoked certificate.
    
    Tracks the revocation details for each revoked certificate.
    """
    
    REVOCATION_REASONS = [
        ('UNSPECIFIED', 'Unspecified'),
        ('KEY_COMPROMISE', 'Key Compromise'),
        ('CA_COMPROMISE', 'CA Compromise'),
        ('AFFILIATION_CHANGED', 'Affiliation Changed'),
        ('SUPERSEDED', 'Superseded'),
        ('CESSATION_OF_OPERATION', 'Cessation of Operation'),
        ('CERTIFICATE_HOLD', 'Certificate Hold'),
        ('REMOVE_FROM_CRL', 'Remove from CRL'),
        ('PRIVILEGE_WITHDRAWN', 'Privilege Withdrawn'),
        ('AA_COMPROMISE', 'AA Compromise'),
    ]
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    # Reference to the certificate
    certificate = models.OneToOneField(
        'UserCertificate',
        on_delete=models.CASCADE,
        related_name='revocation_entry'
    )
    
    # Revocation details
    serial_number = models.CharField(
        max_length=64,
        help_text="Certificate serial number (for CRL generation)"
    )
    revocation_date = models.DateTimeField()
    reason = models.CharField(
        max_length=30, 
        choices=REVOCATION_REASONS,
        default='UNSPECIFIED'
    )
    
    # For CERTIFICATE_HOLD, can be released later
    invalidity_date = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Date when key was known to be invalid"
    )
    
    # CRL inclusion tracking
    first_included_in_crl = models.ForeignKey(
        CertificateRevocationList,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='revocation_entries'
    )
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = "Revoked Certificate"
        verbose_name_plural = "Revoked Certificates"
        ordering = ['-revocation_date']
    
    def __str__(self):
        return f"Revoked: {self.serial_number} ({self.get_reason_display()})"


class OCSPResponse(models.Model):
    """
    Cached OCSP (Online Certificate Status Protocol) responses.
    
    Stores OCSP responses for performance optimization.
    """
    
    CERT_STATUS = [
        ('GOOD', 'Good'),
        ('REVOKED', 'Revoked'),
        ('UNKNOWN', 'Unknown'),
    ]
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    # Request identification
    certificate_serial = models.CharField(max_length=64)
    issuer_name_hash = models.CharField(max_length=64)
    issuer_key_hash = models.CharField(max_length=64)
    
    # Response
    status = models.CharField(max_length=10, choices=CERT_STATUS)
    this_update = models.DateTimeField()
    next_update = models.DateTimeField()
    
    # For revoked status
    revocation_time = models.DateTimeField(null=True, blank=True)
    revocation_reason = models.CharField(max_length=30, blank=True)
    
    # Cached response
    response_der = models.BinaryField(
        help_text="Full OCSP response in DER format"
    )
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = "OCSP Response"
        verbose_name_plural = "OCSP Responses"
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['certificate_serial', 'issuer_key_hash']),
        ]
    
    def __str__(self):
        return f"OCSP: {self.certificate_serial} - {self.status}"
    
    def is_valid(self):
        """Check if cached response is still valid"""
        return timezone.now() < self.next_update
