"""
Django settings for pq_egov_pki project.

Generated by 'django-admin startproject' using Django 3.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import datetime
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', '12va2!$z#&1sjp*6jz8cg+6#*u*eap=8-gcdcsgx8-w7hqkbx7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

# Allowed hosts from environment or default
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

AUTH_USER_MODEL = 'authentication.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_yasg',
    'authentication',
    'hoso',
    'social_auth',
    'pki',  # PKI app for certificate management and post-quantum cryptography
]
CORS_ORIGIN_ALLOW_ALL = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'pki.auth.middleware.TrustedProxyMiddleware',  # Validate proxy headers
    'pki.auth.middleware.ClientCertificateMiddleware',  # Extract client certificates
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pq_egov_pki.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pq_egov_pki.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DATABASE_NAME', 'chinhquyendt'),
        'USER': os.environ.get('DATABASE_USER', 'pnthanh'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', 'pnthanh2001'),
        'HOST': os.environ.get('DATABASE_HOST', 'localhost'),
        'PORT': os.environ.get('DATABASE_PORT', '5432'),
    }
}

REST_FRAMEWORK = {
    'NON_FIELD_ERRORS_KEY': 'error',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# Authentication backends (support both password and certificate auth)
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default password auth
    'pki.auth.backends.CertificateAuthenticationBackend',  # X.509 certificate auth
    'pki.auth.backends.ChallengeResponseAuthBackend',  # Challenge-response auth
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=1),
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
MEDIA_URL = '/hoso/static/'
STATIC_URL = '/static/'
MEDIA_ROOT = BASE_DIR / 'hoso/static/'

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'chinhquyendientudjango@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')


# ============ PKI Configuration ============

# Master key for encrypting CA private keys (MUST be set via environment variable in production)
PKI_MASTER_KEY = os.environ.get('PKI_MASTER_KEY', 'CHANGE_THIS_IN_PRODUCTION_32_BYTES!!')

# Trusted proxy IPs for client certificate headers
TRUSTED_PROXIES = ['127.0.0.1', '::1']

# Challenge expiration time in seconds
PKI_CHALLENGE_EXPIRATION = 300  # 5 minutes

# Default certificate validity periods (in days)
PKI_ROOT_CA_VALIDITY = 3650  # 10 years
PKI_INTERMEDIATE_CA_VALIDITY = 1825  # 5 years
PKI_USER_CERT_VALIDITY = 365  # 1 year
PKI_OFFICER_CERT_VALIDITY = 730  # 2 years

# CRL configuration
PKI_CRL_VALIDITY_DAYS = 7
PKI_CRL_AUTO_GENERATE = True

# Post-quantum algorithm preference
PKI_DEFAULT_PQ_ALGORITHM = 'DILITHIUM3'
PKI_REQUIRE_HYBRID_SIGNATURES = True  # Require both classical and PQ signatures

# PDF signing configuration
PKI_PDF_SIGNATURE_APPEARANCE = True
PKI_PDF_SIGNATURE_REASON = 'Digitally signed by E-Government PKI System'

# Logging configuration for PKI operations
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'pki.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'pki': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}